#!/usr/bin/env python3

import numpy as np
import matplotlib.pyplot as plt
from ase.io import read
from scipy.fft import rfft, rfftfreq
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
import os
import sys

# --- Argument Parser ---
parser = ArgumentParser(
    description="Compute VDOS from ASE trajectory and log file.",
    formatter_class=ArgumentDefaultsHelpFormatter
)
parser.add_argument("traj", help="ASE-readable trajectory file (e.g. .traj, .extxyz)")
parser.add_argument("log", help="Log file with time (fs) and temperature info")
parser.add_argument("-b", "--begin", type=float, default=0.0, help="Start time in ps")
parser.add_argument("-e", "--end", type=float, default=None, help="End time in ps")
parser.add_argument("-mw", "--mass_weighted", action="store_true", help="Use mass-weighted velocities")
parser.add_argument("-a", "--atoms", nargs="+", type=int, default=None, help="Atom indices to include")
parser.add_argument("--plt", action="store_true", help="Show interactive plot")

args = parser.parse_args()

traj_file = args.traj
log_file = args.log
mass_weighted = args.mass_weighted
atom_indices = args.atoms
start_time_ps = args.begin
end_time_ps = args.end
show_plot = args.plt

# --- File check ---
if not os.path.isfile(traj_file):
    sys.exit(f"Error: Trajectory file '{traj_file}' not found.")
if not os.path.isfile(log_file):
    sys.exit(f"Error: Log file '{log_file}' not found.")

# --- Read log ---
log_data = np.loadtxt(log_file, skiprows=1)
time_ps_all = log_data[:, 1] / 1000  # convert fs → ps
start_idx = np.searchsorted(time_ps_all, start_time_ps)
end_idx = np.searchsorted(time_ps_all, end_time_ps, side='right') if end_time_ps else len(time_ps_all)
if start_idx >= end_idx:
    sys.exit(f"Error: No frames between t = {start_time_ps} ps and {end_time_ps or 'end'} ps")

log_data = log_data[start_idx:end_idx]
time_ps = log_data[:, 1] / 1000
dt_fs = (time_ps[1] - time_ps[0]) * 1000
nsteps = len(time_ps)
temperature = log_data[0, 3]

print(f"Time window: {start_time_ps} → {end_time_ps or time_ps[-1]:.3f} ps | dt = {dt_fs:.3f} fs | Steps = {nsteps} | T = {temperature:.1f} K")

# --- Read trajectory ---
images = read(traj_file, index=":")
if len(images) != len(time_ps_all):
    print("Warning: trajectory and log file may be inconsistent in frame count.")
images = images[start_idx:end_idx]

print(f"Number of frames: {len(images)}")
print(f"Atoms per frame: {len(images[0])}")

# --- Extract velocities ---
velocities = []
for i, img in enumerate(images):
    v = img.get_velocities()
    if v is None:
        sys.exit(f"Error: Velocities not found in frame {i} of trajectory!")
    velocities.append(v)
velocities = np.array(velocities, dtype=np.float64)

print(f"Velocities shape: {velocities.shape}")

# --- Atom selection ---
if atom_indices is not None:
    velocities = velocities[:, atom_indices, :]
    print(f"Using atom indices: {atom_indices}")

# --- Mass weighting ---
if mass_weighted:
    masses = images[0].get_masses()
    if atom_indices is not None:
        masses = masses[atom_indices]
    weights = np.sqrt(masses[:, np.newaxis])
    velocities *= weights[np.newaxis, :, :]
    print("Applied mass weighting")

# --- Flatten and remove drift ---
vel_flat = velocities.reshape(nsteps, -1)
vel_flat -= vel_flat.mean(axis=0)

print(f"Velocity stats: min={vel_flat.min():.3e}, max={vel_flat.max():.3e}, mean={vel_flat.mean():.3e}, std={vel_flat.std():.3e}")

# --- Fast VACF using FFT ---
def fast_vacf_fft(x):
    N = x.shape[0]
    f = np.fft.fft(x, n=2*N, axis=0)
    acf = np.fft.ifft(f * np.conjugate(f), axis=0).real[:N]
    acf /= np.arange(N, 0, -1)[:, None]
    acf_total = acf.sum(axis=1)
    return acf_total / x.shape[1]

vacf = fast_vacf_fft(vel_flat)

print(f"VACF (first 20 points): {vacf[:20]}")
print(f"VACF stats: min={vacf.min():.3e}, max={vacf.max():.3e}, mean={vacf.mean():.3e}, std={vacf.std():.3e}")

# --- FFT → VDOS ---
dt_ps = dt_fs * 1e-3
frequencies = rfftfreq(nsteps, dt_ps)
vdos = np.abs(rfft(vacf))
frequencies_cm1 = frequencies * 33.356

vdos /= np.max(vdos)  # normalize for plotting

# --- Plot ---
plt.figure(figsize=(6,4))
plt.plot(frequencies_cm1, vdos, color="royalblue", lw=1)
plt.xlim(0, 4000)
plt.ylim(0, 1.05)
plt.xlabel("Frequency (cm$^{-1}$)")
plt.ylabel("Normalized VDOS (a.u.)")
plt.title(f"VDOS (T = {temperature:.1f} K, t = {start_time_ps}-{end_time_ps or time_ps[-1]:.2f} ps)")
plt.grid(True)
plt.tight_layout()

base_name = os.path.splitext(os.path.basename(traj_file))[0]
range_tag = f"{start_time_ps}-{end_time_ps or 'end'}"
png_name = f"vdos_{base_name}_{range_tag}.png"

if show_plot:
    plt.show()
else:
    plt.savefig(png_name, dpi=300)
    print(f"Saved VDOS plot to: {png_name}")

# --- Save VDOS data (.xvg format) ---
xvg_filename = f"vdos_{base_name}_{range_tag}.xvg"
with open(xvg_filename, "w") as f:
    from datetime import datetime
    now = datetime.now().strftime("%a %b %d %H:%M:%S %Y")
    f.write(f"# Created {now}\n# Generated by FFT-based VDOS script\n")
    f.write("@    title \"Density of states\"\n")
    f.write("@    xaxis  label \"E (cm\\S-1\\N)\"\n")
    f.write("@    yaxis  label \"S(n)\"\n")
    f.write("@TYPE xy\n")
    f.write("@ s0 legend \"DoS(v)\"\n")
    for freq, val in zip(frequencies_cm1, vdos):
        f.write(f"{freq:12.6f} {val:12.6f}\n")

print(f"Saved VDOS data to: {xvg_filename}")

